FNNDSC/pfcon

- pfcon/pfcon.py
The / in front of each of the urls wasn't needed since it's added on the join.
> Cleanup urls and add openshiftlocal

- pfcon/pfcon.py
@rudolphpienaar I'm not 100% sure this is right fix but it does solve the problem we are seeing.  The issue is that the status call is happening before there is a valid status to report.
> Handle case where status isn't available yet

- Dockerfile
- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Dockerfile: merge with @danmcp changes
pfcon/pfcon.py:
* Add pfmisc to handle/abstract out debug reporting
** Changes from self.qprint to self.dp.qprint
* Updates to status handling
* Updates to creating summary reports
> PR: Initial merge with dev

- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Fixes an error when pfcon checks for status on remote compute job too early.
> Fix timing on later start of compute

- pfcon/pfcon.py
@rudolphpienaar I am not sure where the new code changes are at, but these urls are wrong and I was hoping to get fixed for testing purposes.
> Fix moc urls

- .travis.yml
- CUBE_CI.sh
> Added integration tests to the travis yml

- .travis.yml
- cube_before_install.sh
- cube_before_script.sh
> Modified to correctly run CUBE using docker swarm

- pfcon/pfcon.py
@danmcp @rudolphpienaar 
modified pfcon to use the new pfurl syntax. Nothing crazy
was tested with hello call to local pfioh and pman
> Pfurl urls

- pfcon/pfcon.py
@iamemilio @rudolphpienaar FYI
> Reverting https changes

- Dockerfile
- README.rst
- bin/pfcon
- config.json
- decorate.sh
- docker-compose.yml
- make
- pfcon/pfcon.py
- setup.py
- swiftCtl.sh
- unmake
Hi all -- this PR shouldn't affect current pfcon.  It adds some JSON to internal var for swift client connection, as well as some methods to handle swift put_object. Right now, the code will not execute the swift parts (turned off with an ``and False`` in line 1134, so there should be no impact on pfcon images.
I'd like to commit so that I can continue debugging/developing -- the pfcon docker image does not have the python-swiftclient, so if I can do this PR that should add it.
I'll test the e2e and email again.
> Initial swift support

- docker-compose.yml
- make
- pfcon/pfcon.py
More fixes and updates to swift as well as refactor of the main coordinating method of pfcon. Now better organized and more readable.
> More swift based improvements

- pfcon/pfcon.py
Closes: https://github.com/redhat-university-partnerships/radiology/issues/52
Depends on: https://github.com/FNNDSC/pfioh/pull/36
> Remove encoding option from pfcon

- bin/pfcon
- pfcon/pfcon.py
Print logs by default
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Set --verbosity to 1 by default

- config.json
- pfcon/pfcon.py
> k-openshift-env routes for pman & pfioh

- Dockerfile
- README.rst
- bin/pfcon
- docker-compose.yml
- pfcon/pfcon.py
- setup.py
- swiftCtl.sh
> Add proxy support, clean in-line comment help, fix SWIFTIP parsing

- .travis.yml
- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Inject `serviceType` in data JSON description for downstream `pfioh` processing.
> Handle `serviceType` requests

- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Add logic for handling 'False' returns on computeStatusRequest
Bump to 2.2.4.2
Fix some typos in comments
> Add logic for dealing with possible spurious return from remote compute

- .env
- README.rst
- bin/pfcon
- docker-compose_dev.yml
- make.sh
- setup.py
- unmake.sh
Bump to 2.2.4.4
Fixed some formatting and spurious copy/paste issues
Fix incorrect name on swift_storage_dev
Fix some rebase weirdness, format, and add file/dir push to swift
> Update for fnndsc repos

- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Fix handling login on jobSummary return for 'compute' state
> Bump to 2.2.6.0

- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Fix minor logic issue in compute.status
> Minor logic fix to compute.status and bump version

- README.rst
- bin/pfcon
- pfcon/pfcon.py
- setup.py
Fix log in looking job return status and minor beautification
> Bump to 2.2.6.4

- .dockerignore
- .gitignore
- deploy.sh
- kubernetes/pfcon_prod.yaml
- make.sh
- unmake.sh
The default `STOREBASE` folder is now `./CHRIS_REMOTE_FS`
> Fix implementation of -S <storeBase> option in shell scripts

- Dockerfile
- kubernetes/pfcon_dev.yaml
- pfcon/resources.py
- requirements/base.txt
- requirements/local.txt
- swarm/docker-compose_dev.yml
- pfcon's API now accepts an optional `env` list field
> Fix pfcon development environment and update pfcon's API to accept an optional env list field

- pfcon/config.py
fixes https://github.com/FNNDSC/pfcon/issues/132
> fix: log debug lines in pfcon to stdout
